defmodule TodoAbsinthe.Todo.Item do
  use Ecto.Schema
  import Ecto.Changeset


  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "todos" do
    field :completed, :boolean, default: false
    field :order, :integer, read_after_writes: true # autogenerated by PostgreSQL
    field :title, :string

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset_for_create(item, attrs) do
    item
    |> cast(attrs, [:id, :title, :order, :completed])
    |> validate_required([:title, :completed])
  end

  @doc false
  def changeset(item, attrs) do
    item
    |> cast(attrs, [:title, :order, :completed])
    |> validate_required([:title, :completed])
  end
end
